spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/laboBE_db
    username: postgres
    password: test1234=
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: springbootfelix@gmail.com
    password: aotanwihokxtxtxf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


springdoc:

  swagger-ui:
    path: /swagger